### ISSUE TITLE
reason for passing React for construction?

### ISSUE THREAD

**Issue by phated** [af/JSnoX#5]
I was just wondering the reasoning behind passing React into the exported module.  It seems like you can just require it because you have React as a peerDep and only support `React.createElement`.  I currently have a file that just imports the 2 and exports a jsnox client and would like to remove that file.

**Comment by af** [comment]
Hi,
The thinking there was to make the dependency on React explicit by passing it in. It also keeps open the possibility of mocking `React.createElement` for tests if necessary (although I haven't had any reason to do that yet). You're right that the peer dependency means we could omit the parameter, but I'd like to keep it since it's only a minor annoyance.

For a quick one-liner, you can always do:
```var d = require('jsnox')(require('react'))```
It's obviously not as succinct, but it should work fine.

**Comment by phated** [comment]
Thanks for the reply.  I would say that `React.createElement` is easily mock-able with something like Jest or Sinon because it is attached to the `React` namespace.  The one liner is actually worse for us because it goes against our styleguide.
